In [1]:
'''
Created on Mar 22, 2018

@author: BVR
'''


# a is 2-D matrix with integers
a = [['Roy',80,75,85,90,95],
     ['John',75,80,75,85,100],
     ['Dave',80,80,80,90,95]]

#b is a nested list but not a matrix
b= [['Roy',80,75,85,90,95],
    ['John',75,80,75],
    ['Dave',80,80,80,90,95]]


In [2]:

n = 3
m = 4
a = [0] * n
for i in range(n):
    a[i] = [0] * m
print(a)


[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [3]:

from numpy import * 

x = range(16)

x = reshape(x,(4,4)) 

print(x) 



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:

# a is 2-D matrix with integers
a = [['Roy',80,75,85,90,95],
     ['John',75,80,75,85,100],
     ['Dave',80,80,80,90,95]]

print(a[0])

print(a[0][1])

print(a[1][2])

['Roy', 80, 75, 85, 90, 95]
80
80


In [5]:

#negative matrix


a = [['Roy',80,75,85,90,95],
     ['John',75,80,75,85,100],
     ['Dave',80,80,80,90,95]]
    
print(a[-1]) 
    
print(a[-1][-2]) 

print(a[-2][-3]) 


['Dave', 80, 80, 80, 90, 95]
90
75


In [6]:

from numpy import *

a = array([['Roy',80,75,85,90,95],
           ['John',75,80,75,85,100],
           ['Dave',80,80,80,90,95]])

print(a[:3,[0,1]])




[['Roy' '80']
 ['John' '75']
 ['Dave' '80']]


In [7]:

a = [['Roy',80,75,85,90,95],
     ['John',75,80,75,85,100],
     ['Dave',80,80,80,90,95]]

b=a[0]
print(b)

b[1]=75
print(b)

a[2]=['Sam',82,79,88,97,99]
print(a)

a[0][4]=95
print(a)


['Roy', 80, 75, 85, 90, 95]
['Roy', 75, 75, 85, 90, 95]
[['Roy', 75, 75, 85, 90, 95], ['John', 75, 80, 75, 85, 100], ['Sam', 82, 79, 88, 97, 99]]
[['Roy', 75, 75, 85, 95, 95], ['John', 75, 80, 75, 85, 100], ['Sam', 82, 79, 88, 97, 99]]


In [9]:


from numpy import *

a = array([['Roy',80,75,85,90,95],
           ['John',75,80,75,85,100],
           ['Dave',80,80,80,90,95]])

a= append(a,[['Sam',82,79,88,97,99]],0)

    #here 0 is axis that represents the dimensions where 0 stands for row and 1 stands for column

print(a)


[['Roy' '80' '75' '85' '90' '95']
 ['John' '75' '80' '75' '85' '100']
 ['Dave' '80' '80' '80' '90' '95']
 ['Sam' '82' '79' '88' '97' '99']]


In [10]:

from numpy import * 

a = array([['Roy',80,75,85,90,95],
      ['John',75,80,75,85,100],
      ['Dave',80,80,80,90,95]]) 

a= insert(a,[6],[[73],[80],[85]],axis=1) 
#here axis represents the dimensions where 0 stands for row and 1 stands for column 

print(a) 


[['Roy' '80' '75' '85' '90' '95' '73']
 ['John' '75' '80' '75' '85' '100' '80']
 ['Dave' '80' '80' '80' '90' '95' '85']]


In [11]:


a=[['Roy',80,75,85,90,95],
    ['John',75,80,75,85,100],
    ['Dave',80,80,80,90,95]]

a= a+ [['Sam',82,79,88,97,99]]

print(a)



[['Roy', 80, 75, 85, 90, 95], ['John', 75, 80, 75, 85, 100], ['Dave', 80, 80, 80, 90, 95], ['Sam', 82, 79, 88, 97, 99]]


In [12]:

from numpy import *

a = array([['Roy',80,75,85,90,95],
      ['John',75,80,75,85,100],
      ['Dave',80,80,80,90,95]])

a= delete(a,[1],0)

print(a)


[['Roy' '80' '75' '85' '90' '95']
 ['Dave' '80' '80' '80' '90' '95']]


In [13]:

from numpy import *

a = array([['Roy',80,75,85,90,95],
      ['John',75,80,75,85,100],
      ['Dave',80,80,80,90,95]])

a= delete(a, s_[1::2], 1)

print(a)



[['Roy' '75' '90']
 ['John' '80' '85']
 ['Dave' '80' '90']]
